// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fetch from "bs-fetch/src/Fetch.res.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_promise from "rescript/lib/es6/js_promise.js";

var baseUrl = "http://localhost:3000/";

function fetchClothing() {
  var requestInit = Fetch.RequestInit.make("Get", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)();
  return Js_promise.then_((function (response) {
                if (response.ok) {
                  return Js_promise.then_((function (data) {
                                console.log(data);
                                return Promise.resolve(data);
                              }), Fetch.$$Response.json(response));
                } else {
                  return Promise.reject(Js_exn.raiseError("Erreur lors de la récupération des vêtements."));
                }
              }), fetch(baseUrl + "/clothing", requestInit));
}

export {
  baseUrl ,
  fetchClothing ,
}
/* No side effect */
