// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Category(props) {
  var name = props.name;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "card-img-top",
                      alt: name,
                      src: props.image
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h5", {
                              children: name,
                              className: "card-title"
                            }),
                        JsxRuntime.jsx("p", {
                              children: props.description,
                              className: "card-text"
                            })
                      ],
                      className: "card-body"
                    })
              ],
              className: "card text-center"
            });
}

var make = Category;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
