// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as React from "react";
import * as Header from "./Header.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ClothingList(props) {
  var match = React.useState(function () {
        return [];
      });
  var setClothingList = match[1];
  React.useEffect((function () {
          var makeRequest = async function () {
            var data = await Api.fetchClothing();
            return setClothingList(function (param) {
                        return data;
                      });
          };
          makeRequest();
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {}),
                JsxRuntime.jsx("h1", {
                      children: "Liste des vêtements",
                      className: "text-center my-4 display-4 fw-bold"
                    }),
                JsxRuntime.jsx("div", {
                      children: match[0].map(function (clothing) {
                            return JsxRuntime.jsx("div", {
                                        children: JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("div", {
                                                      children: JsxRuntime.jsx("img", {
                                                            className: "card-img-top",
                                                            style: {
                                                              height: "200px",
                                                              width: "45%",
                                                              objectFit: "cover"
                                                            },
                                                            alt: clothing.name,
                                                            src: "/src/assets/Images/" + clothing.imageUrl
                                                          }),
                                                      className: "d-flex justify-content-center"
                                                    }),
                                                JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx("p", {
                                                              children: clothing.name,
                                                              className: "card-title"
                                                            }),
                                                        JsxRuntime.jsx("a", {
                                                              children: clothing.price.toString() + " €",
                                                              className: "btn btn-secondary",
                                                              href: "#"
                                                            })
                                                      ],
                                                      className: "card-body"
                                                    })
                                              ],
                                              className: "card text-center",
                                              style: {
                                                width: "100%"
                                              }
                                            }),
                                        className: "col-3 mb-4 d-flex justify-content-center"
                                      }, clothing.id.toString());
                          }),
                      className: "row justify-content-center",
                      style: {
                        margin: "0 auto",
                        width: "95%"
                      }
                    })
              ]
            });
}

var make = ClothingList;

export {
  make ,
}
/* react Not a pure module */
