// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Footer(props) {
  return JsxRuntime.jsx("footer", {
              children: JsxRuntime.jsx("p", {
                    children: "© 2023 Boutique de Vêtements. Tous droits réservés."
                  }),
              className: "bg-dark text-white p-4 text-center"
            });
}

var make = Footer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
