// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Header(props) {
  return JsxRuntime.jsxs("nav", {
              children: [
                JsxRuntime.jsx("a", {
                      children: "Boutique",
                      className: "navbar-brand",
                      href: "#"
                    }),
                JsxRuntime.jsx("button", {
                      children: JsxRuntime.jsx("span", {
                            className: "navbar-toggler-icon"
                          }),
                      "aria-label": "Toggle navigation",
                      "aria-expanded": false,
                      "aria-controls": "navbarNav",
                      className: "navbar-toggler",
                      type: "button"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("ul", {
                            children: props.categories.map(function (category) {
                                  return JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsx("a", {
                                                    children: category.name,
                                                    className: "nav-link",
                                                    href: "#" + category.name
                                                  }),
                                              className: "nav-item"
                                            });
                                }),
                            className: "navbar-nav ml-auto"
                          }),
                      className: "collapse navbar-collapse",
                      id: "navbarNav"
                    })
              ],
              className: "navbar navbar-expand-lg navbar-light bg-light"
            });
}

var make = Header;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
