// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Header(props) {
  return JsxRuntime.jsx("header", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h1", {
                            children: "Boutique de Vêtements",
                            className: "text-2xl font-bold"
                          }),
                      JsxRuntime.jsxs("nav", {
                            children: [
                              JsxRuntime.jsx("a", {
                                    children: "Catégories",
                                    className: "hover:text-gray-300",
                                    href: "./categorie"
                                  }),
                              JsxRuntime.jsx("a", {
                                    children: "Marque",
                                    className: "hover:text-gray-300",
                                    href: "./marque"
                                  }),
                              JsxRuntime.jsx("a", {
                                    children: "Contact",
                                    className: "hover:text-gray-300",
                                    href: "#contact"
                                  })
                            ],
                            className: "space-x-4"
                          })
                    ],
                    className: "container mx-auto flex justify-between items-center"
                  }),
              className: "bg-gray-900 text-white p-4"
            });
}

var make = Header;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
