// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Header(props) {
  return JsxRuntime.jsx("header", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h1", {
                            children: "NOÏA Shop",
                            className: "h2 fw-bold text-white"
                          }),
                      JsxRuntime.jsx("nav", {
                            children: JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("a", {
                                          children: "Catégories",
                                          className: "text-white me-3",
                                          href: "./categorie"
                                        }),
                                    JsxRuntime.jsx("a", {
                                          children: "Marque",
                                          className: "text-white me-3",
                                          href: "./marque"
                                        }),
                                    JsxRuntime.jsx("a", {
                                          children: "Contact",
                                          className: "text-white",
                                          href: "#contact"
                                        })
                                  ],
                                  className: "d-flex"
                                }),
                            className: "navbar",
                            style: {
                              backgroundColor: "#424547"
                            }
                          })
                    ],
                    className: "container d-flex justify-content-between align-items-center"
                  }),
              className: "p-3",
              style: {
                backgroundColor: "#424547"
              }
            });
}

var make = Header;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
