// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ProductCard(props) {
  var name = props.name;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "card-img-top",
                      alt: name,
                      src: props.image
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h5", {
                              children: name,
                              className: "card-title"
                            }),
                        JsxRuntime.jsx("p", {
                              children: props.description,
                              className: "card-text"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: props.price + " €",
                                      className: "text-success"
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Acheter",
                                      className: "btn btn-primary"
                                    })
                              ],
                              className: "d-flex justify-content-between align-items-center"
                            })
                      ],
                      className: "card-body"
                    })
              ],
              className: "card"
            });
}

var make = ProductCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
