// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ProduitPage(props) {
  var product = props.product;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("img", {
                                  className: "img-fluid rounded",
                                  alt: product.name,
                                  src: product.image
                                }),
                            className: "col-md-6"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h2", {
                                    children: product.name,
                                    className: "font-bold text-3xl"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: product.description,
                                    className: "text-muted"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: product.price + " €",
                                    className: "text-lg font-semibold"
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Acheter",
                                    className: "btn btn-primary mt-4"
                                  })
                            ],
                            className: "col-md-6"
                          })
                    ],
                    className: "row"
                  }),
              className: "container my-4"
            });
}

var make = ProduitPage;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
