// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HelloWorld from "../components/HelloWorld.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsx(HelloWorld.make, {
              name: "Mika"
            });
}

var make = Home;

export {
  make ,
}
/* HelloWorld Not a pure module */
