// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./page/Home.res.mjs";
import * as MarqueList from "./components/MarqueList.res.mjs";
import * as ClothingList from "./components/ClothingList.res.mjs";
import * as CategorieList from "./components/CategorieList.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return JsxRuntime.jsx(Home.make, {});
  }
  switch (match.hd) {
    case "categorie" :
        if (match.tl) {
          return JsxRuntime.jsx(Home.make, {});
        } else {
          return JsxRuntime.jsx(CategorieList.make, {});
        }
    case "clothing" :
        if (match.tl) {
          return JsxRuntime.jsx(Home.make, {});
        } else {
          return JsxRuntime.jsx(ClothingList.make, {});
        }
    case "marque" :
        if (match.tl) {
          return JsxRuntime.jsx(Home.make, {});
        } else {
          return JsxRuntime.jsx(MarqueList.make, {});
        }
    default:
      return JsxRuntime.jsx(Home.make, {});
  }
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
