// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./page/Home.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  RescriptReactRouter.useUrl(undefined, undefined);
  return JsxRuntime.jsx(Home.make, {});
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
